### ISSUE TITLE
Is it safe to have the access token inside the app?

### ISSUE THREAD

**Issue by radiKal07** [data-hfg/contentful.dart#13]
From you example I see you have the access token in Dart (`Secrets.accessToken`).
Is it safe to have this token here?

**Comment by minikin** [comment]
@tudor07 For an example app it works. 
There were no reasons to add additional complexity to demo this project. 

There’s no way to secure secrets stored on the client (mobile apps in this case)
It can be reverse-engineered, anyway. We can just make it harder using different technics like  [Obfuscating](https://github.com/flutter/flutter/wiki/Obfuscating-Dart-Code) etc.
